### ISSUE TITLE
gopro_hd2.exif is not included in the gem

### ISSUE THREAD

**Issue by p8952** [remvee/exifr#41]
`tests/data/gopro_hd2.exif` is missing from the gem hosted at https://rubygems.org, causing tests to fail unless this is downloaded separately.

I can see other data files referenced in tests are included, so I'm presuming gopro_hd2.exif should be as well?

```
$ rake test
Run options: --seed 6089

# Running:

..............E..................

Finished in 0.537711s, 61.3713 runs/s, 5843.2909 assertions/s.

  1) Error:
TIFFTest#test_nul_terminated_strings:
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/peter/downloads/tests/data/gopro_hd2.exif
    /home/peter/downloads/lib/exifr/tiff.rb:610:in `initialize'
    /home/peter/downloads/lib/exifr/tiff.rb:610:in `open'
    /home/peter/downloads/lib/exifr/tiff.rb:610:in `initialize'
    /home/peter/downloads/lib/exifr/tiff.rb:623:in `new'
    /home/peter/downloads/lib/exifr/tiff.rb:623:in `open'
    /home/peter/downloads/lib/exifr/tiff.rb:373:in `initialize'
    /home/peter/downloads/tests/tiff_test.rb:195:in `new'
    /home/peter/downloads/tests/tiff_test.rb:195:in `test_nul_terminated_strings'

33 runs, 3142 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:tests" -I"/home/peter/.gem/ruby/2.1.0/gems/rake-10.4.2/lib" "/home/peter/.gem/ruby/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "tests/jpeg_test.rb" "tests/tiff_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by remvee** [comment]
Thanks!
